services:
  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./auth-service:/app
    depends_on:
      - auth-db
    networks:
      - app-network

  auth-db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  hospital-service:
    build:
      context: .
      dockerfile: hospital-service/Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./hospital-service:/app
    depends_on:
      - hospital-db
    networks:
      - app-network

  hospital-db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hospital_db
    ports:
      - "5434:5432"
    volumes:
      - hospital_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  personnel-service:
    build:
      context: .
      dockerfile: personnel-service/Dockerfile
    ports:
      - "8083:8083"
    volumes:
      - ./personnel-service:/app
    depends_on:
      - personnel-db
    networks:
      - app-network

  personnel-db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: personnel_db
    ports:
      - "5435:5432"
    volumes:
      - personnel_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheuss
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - app-network
    depends_on:
      - auth-service
      - hospital-service
      - personnel-service

  grafana:
    image: grafana/grafana:latest
    container_name: grafanaa
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - prometheus

  redis:
    image: redis:6.2
    container_name: redis_cach
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  auth_postgres_data:
  hospital_postgres_data:
  personnel_postgres_data:
  redis_data:


networks:
  app-network:
    driver: bridge
