server:
  port: "8082"

database:
  host: "postgres"
  port: "5432"
  user: "user"
  password: "password"
  dbname: "hospital_db"
  sslmode: "disable"

redis:
  addr: "redis:6379"
  password: ""
  db: 0

jwt:
  secret: "your_super_secret_key"