server:
  port: "8082"

database:
  host: "hospital-db"
  port: "5432"
  user: "user"
  password: "password"
  dbname: "hospital_db"
  sslmode: "disable"

redis:
  addr: "redis:6379"
  password: ""
  db: 0

jwt:
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIJJgIBAAKCAgBQh2L3F2ul45g+/prIa106mC+AT//VN5yBU5/vLX/Zbhn7dfwp
    rpq/KviDt5pgw/aM0eomRjdZF8+vIT0K7jrQe3Gs6hTztEhLyArcfaAZUDpj+OBn
    HODmWR2RbJ0bO5rGjxT+AU71oCmxGB6nNJV9ZPDB+NGchRrHqvGgD49nEL7BQ2TQ
    tgqnza4bvk5EXnympoO60J4OTocUj4q3Qg+lpLFkBfeK0qUGKHPiCMol8pKsRHXz
    OxWxehgjLlh65MT8dS6pkzq9OGB0XNeDV/0FPdYwwTZbRuba59iKBhdTjUxTte3E
    PB1UD+MxxRzIiskmplmQR7XIKsu60FcXTEKfwQ5jxF0SulnWJWf1XJCcCMfQjrWq
    3Kfwh526qFRePNNjQjvH1D4BTw1ZFfyWOO5dK3uPgK39DWIEDmKKSE6eDZPrZJ6T
    4txBT6UJzQGpRzzpMsxGG3IYRvl3vjn9GKdXkNEj45jTzNJOPKdxovPyTWKCUI8Q
    ivE+GLkeU4MA7aI6a1drCzcaD1mAMnK0VCOPRNaPyn3pBf4fx02hbl7VOb2lDQid
    +sPWWqIBbZDb0tT5ya+u3j5x5UPwD2j3g9epBp75NhK8ZkZDNM1f2ZQpU9hbpghw
    iby91BnpT3ukOX5bMX3WC9dg1B5NtJjVz44hPLo46tNqYUWX2xZgUVd91QIDAQAB
    AoICAAiriuwviVeC+ZFOuDt7073LRNH7yv+ZzS/fYQjPTUSLpiB8w3l5Yw/SAI+t
    5OEmOBVRRHR6etsMxT+FxJy4qXxozgRf74GNl3sRPpoerG4NRTweP4ragRxL2/Mc
    To3wDOnz3b67RVUMuXBnuGUoNDAb/g/kSi0f55I3xWwGQNpH40HLj78o2lzWuDgk
    dSjHQ4RtySED9QB1U/XSvoycgDLFWJP8UHqR01KmaFOdvqX3R/NkK47UfbFuA8tF
    4iDZIJxNwYhgYaKdv0TH+iwZ/RPjZHw7US7io1hOPfIeVcSZIe6hV8gY8M9sJnnl
    TwQIbT/MCTiPf/LdKLIkXDwV6dZKczphi8Ayehr8Ajfmg/V2U1my4GoeXCRwuXRh
    cVapCYe7vmeiIvDF9jaL9+5MQMRhMls619Ki4RtT2vMSGOyyITqGFjWcMfs/Qge9
    HSiY3ZzIBTuaZEEFUcoCEeHGPOa3ay06l4KsxQlvehCD/GbBYpv0WlWKDy1kAPRj
    Hz2LPdqhWhdPYrPcB7i84+T+06srUlBpW8jHDBQhMMlaY2/cLDjJj8Ib9KY5tcQH
    rAFN7nKTSAl/Eq9E4L2SuiEMAZ8+4un+OYjRiUp7bzwuNE1wWqrcyveFjaSLP9+z
    SYnr8higAt+HYTQ7q4UWtIh+LEpmpjqhQ27u7Kr+6ty0VPTBAoIBAQCUnyIXESzA
    d5NpG49T9xoNL7BWiC5oy8ETEkgFgZe26goN8Jey7mdowCub8WNRZZRG0i6iIlbD
    Qahr2hqhAtJGL8m1jnglfvaoJtE+af3UbCzctEZvII6v9GrwBPMTL+mvrDIRiCQO
    UG+dNfsOUDJ7pKtEN3irHGHeT6aVruOfWvxPyPGGcBWeAyiT56a8cxvlj0Jky+Be
    jIaMTg3uzje/vWFGUiSjS0y+faHrzVKvw/8wfTXKpUH83yvdgBpvAFabxwkODDJO
    H+Jg5JBOWL4xw151MJvpdaJz55POic/SCocbFxZMP6ov8HZHdK1ZAuNMG/6PUsPt
    CwpulLQE1Uj/AoIBAQCKtebyJ0OAL48juo0wzeYJNNwTPUTE5xz+MwbZLsfjXWuW
    wXy8gEHr2l2UOK+PVRjuSSUt9o2FM5RYAFkfBi4QB1+IJJT6Cpc8MxUteLIyJ5sL
    IuWQdbHgpCGQPjAKKJeExrw0k/p5Jez4tor4BE2KlLicE+WAdWNedoPIuffGByy4
    s0/1nIXwoHke9KKumEmc5xgl+oTHMesuDIuL3zDv/AVz+M7UnQejQOZGjTk/hQ9v
    BCZjQ+n5Ok0RH0snUfq+W2OiYgCx59Qs9CT4WS6XoRATm01Z2ZtX6Ms68xeLAeKG
    BT3s2E7YbtRxb6bp479I1L+Zr6nZ+cHUNAuHqMUrAoIBAG/AECQEGABIaSD5RhY+
    kOolV5RZJXxK6MxsTJdHUEqLRDAjHg2+0SakiKXjJWjI1mtCEyp6Y37B2d/uyWMT
    +gQoXqUTkSewhcr+FQu3KtMU287ABs38Tw3i3J3JOvTMbAxZj/Q6x9GzjZlKQ5IJ
    n0v1D4plo2gWGUjN31ZhgGoMQffEAkex868ydMpxvp+odetwgt3DptuxEmJhNny/
    to+H2KLFlSLrtbLuSFhDtM7QswtEurO6+xkmvZb5gebA/F55lEdpyFGSC+gLNK6U
    b75/RoEbocAzYYmBMVR1rzwiCmDGRU/j9xXA207zXny1fS93RTuDYirUyG1Jhuqz
    bQUCggEAV+yx9bEZwnljHFy1/selFxTgo3lkzANLh35EywoyPlcLScZgEQSjxKLo
    SnocHpjscq7+2EG+tz5Yu+eMlnPOYu6piZzWqiBoeQpQVEB7g/tC9i4qogVYuXKQ
    q+Qfg3DzioCG8DUUwhJeQdFECa6AkGVxF84s3d6LHGe3ZVcsTeRiXrma569N35d4
    7zxWmqGBl+mMjxZbcACeeNQO6JyTYqu3sSl3waHAI6WR0grWzQLFI7PXuXhlKUvh
    agcSFlyKunsnjtjcY+j1v4EKpjmxpP+9NxBsWZXsOC8iE73foIeTVSyhci4y3FJ0
    a2tAvGVW7Q2eXgbRfZApYx+SZ219fQKCAQB/sWsObN8YPcmetVpqLxiEGgVrg7p9
    5bpaH28NNSKl6CC0s9qYV0rFWxHF7LhNNwF1oo2W13amn1a5w3l0N2HUfn8MHnMW
    lXNH1uhJT8H9dWU5V5/AjACEQcH6A5z4264GTvKl3cwY0vecFEa0L1oIYjXz6uHY
    RfJT+PY7nNPqiholKgR9PTs3xuxI63CIb8DxLMC50SkJBTds2cpX0LHZrzjW64oN
    blVmohcYJ7Z1r6zKXQKaPNUt3SB2n+LX3VnQk5oTs7QIwv6cDSGphsQE/IV3H+QS
    ES4teDzGlJVD2OR0y43LzelwmBH4fmgWbmsXKUoPXEerRCHrAsZoU4Bh
    -----END RSA PRIVATE KEY-----
  public_key: |
    -----BEGIN PUBLIC KEY-----
    MIICITANBgkqhkiG9w0BAQEFAAOCAg4AMIICCQKCAgBQh2L3F2ul45g+/prIa106
    mC+AT//VN5yBU5/vLX/Zbhn7dfwprpq/KviDt5pgw/aM0eomRjdZF8+vIT0K7jrQ
    e3Gs6hTztEhLyArcfaAZUDpj+OBnHODmWR2RbJ0bO5rGjxT+AU71oCmxGB6nNJV9
    ZPDB+NGchRrHqvGgD49nEL7BQ2TQtgqnza4bvk5EXnympoO60J4OTocUj4q3Qg+l
    pLFkBfeK0qUGKHPiCMol8pKsRHXzOxWxehgjLlh65MT8dS6pkzq9OGB0XNeDV/0F
    PdYwwTZbRuba59iKBhdTjUxTte3EPB1UD+MxxRzIiskmplmQR7XIKsu60FcXTEKf
    wQ5jxF0SulnWJWf1XJCcCMfQjrWq3Kfwh526qFRePNNjQjvH1D4BTw1ZFfyWOO5d
    K3uPgK39DWIEDmKKSE6eDZPrZJ6T4txBT6UJzQGpRzzpMsxGG3IYRvl3vjn9GKdX
    kNEj45jTzNJOPKdxovPyTWKCUI8QivE+GLkeU4MA7aI6a1drCzcaD1mAMnK0VCOP
    RNaPyn3pBf4fx02hbl7VOb2lDQid+sPWWqIBbZDb0tT5ya+u3j5x5UPwD2j3g9ep
    Bp75NhK8ZkZDNM1f2ZQpU9hbpghwiby91BnpT3ukOX5bMX3WC9dg1B5NtJjVz44h
    PLo46tNqYUWX2xZgUVd91QIDAQAB
    -----END PUBLIC KEY-----
  access_token_expiry: "12h"
  refresh_token_expiry: "168h"

personnel_service:
  base_url: "http://personnel-service:8083"